# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         LWP-Protocol-sftp
version:      0.01
version_from: lib/LWP/Protocol/sftp.pm
installdirs:  site
requires:
    LWP:                           0
    Net::SFTP::Foreign:            0
    Sort::Key:                     0.02
    URI::sftp:                     0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
