--- #YAML:1.0
name:                LWP-Protocol-sftp
version:             0.04
abstract:            adds SFTP support to LWP
license:             ~
author:              
    - Salvador Fandino <sfandino@yahoo.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    LWP:                           0
    Net::SFTP::Foreign:            1.40
    URI::sftp:                     0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
